#!/bin/bash
#
# phire-console main Linux/Unix CLI bash script
#

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
CYG_PATH="$( which cygpath 2> /dev/null )"

if [ "$CYG_PATH" != "" ]; then
    SCRIPT_PATH="$( cygpath -w $SCRIPT_DIR )\\phire.php $@"
    SCRIPT_PATH=${SCRIPT_PATH//\\/\/}
else
    SCRIPT_PATH="$SCRIPT_DIR/phire.php $@"
fi

TIMESTAMP=$(date +%Y-%m-%d)
TAR="$(which tar 2> /dev/null)"
ZIP="$(which zip 2> /dev/null)"

MYSQL_CLI=`which mysql 2> /dev/null`
MYSQL_DUMP=`which mysqldump 2> /dev/null`
PGSQL_CLI=`which psql 2> /dev/null`
PGSQL_DUMP=`which pg_dump 2> /dev/null`
SQLITE_CLI=`which sqlite3 2> /dev/null`
SQLITE_DUMP=`which sqlite3 2> /dev/null`

TAR=${TAR// /\\ }
ZIP=${ZIP// /\\ }
MYSQL_CLI=${MYSQL_CLI// /\\ }
MYSQL_DUMP=${MYSQL_DUMP// /\\ }
PGSQL_CLI=${PGSQL_CLI// /\\ }
PGSQL_DUMP=${PGSQL_DUMP// /\\ }
SQLITE_CLI=${SQLITE_CLI// /\\ }
SQLITE_DUMP=${SQLITE_DUMP// /\\ }

if [ "$1" = "sql" ] || [ "$1" = "archive" ]; then
    if [ "$1" = "sql" ] && [ "$2" = "" ]; then
        echo;
        echo "    You must enter a SQL command. Try ./phire help for help."
        echo;
    fi;

    if [ "$2" = "cli" ]; then
        DBTYPE=`php $SCRIPT_PATH`
        DBSTRING=`php $SCRIPT_PATH $DBTYPE`
        if [ "$DBTYPE" = "mysql" ] && [ "$MYSQL_CLI" != "" ] && [ "$DBSTRING" != "" ]; then
            eval "$MYSQL_CLI $DBSTRING"
        elif [ "$DBTYPE" = "pgsql" ] && [ "$PGSQL_CLI" != "" ] && [ "$DBSTRING" != "" ]; then
            eval "$PGSQL_CLI $DBSTRING"
        elif [ "$DBTYPE" = "sqlite" ] && [ "$SQLITE_CLI" != "" ] && [ "$DBSTRING" != "" ]; then
            eval "$SQLITE_CLI $DBSTRING"
        else
            echo;
            echo "    The SQL CLI client could not be found."
            echo;
        fi
    elif [ "$1" = "archive" ] || [ "$2" = "dump" ]; then
        DBTYPE=`php $SCRIPT_PATH`
        DBSTRING=`php $SCRIPT_PATH $DBTYPE`
        if [ "$DBTYPE" = "mysql" ] && [ "$MYSQL_DUMP" != "" ] && [ "$DBSTRING" != "" ]; then
            eval "$MYSQL_DUMP $DBSTRING"
            echo;
            echo "    The MySQL database has been dumped."
            echo;
        elif [ "$DBTYPE" = "pgsql" ] && [ "$PGSQL_DUMP" != "" ] && [ "$DBSTRING" != "" ]; then
            eval "$PGSQL_DUMP $DBSTRING"
            echo;
            echo "    The PostgreSQL database has been dumped."
            echo;
        elif [ "$DBTYPE" = "sqlite" ] && [ "$SQLITE_DUMP" != "" ] && [ "$DBSTRING" != "" ]; then
            eval "$SQLITE_DUMP $DBSTRING"
            echo;
            echo "    The SQLite database has been dumped."
            echo;
        else
            echo;
            echo "    The SQL CLI dump client could not be found."
            echo;
        fi

        if [ "$1" = "archive" ]; then
            if [ "$TAR" != "" ]; then
                "$TAR" -cvzpf "phirecms_$TIMESTAMP.tar.gz" --exclude="phirecms_$TIMESTAMP.tar.gz" ../.htaccess ../*
                rm -f *.sql
            elif [ "$ZIP" != "" ]; then
                "$ZIP" -r -v --exclude="phirecms_$TIMESTAMP.zip" "phirecms_$TIMESTAMP.zip" ../.htaccess ../*
                rm -f *.sql
            else
                echo;
                echo "    An archive program could not be found."
                echo;
            fi
        fi
    fi
else
    php $SCRIPT_PATH
fi;
